### ISSUE TITLE
Fibonacci Code

### ISSUE THREAD

**Issue by Bernardoow** [PacktPublishing/NodeJS-Web-Development#1]
I try calc fibo with 1 and 2. But Happend a error with max stack~.
So, I put console.log And see number -100, -101.

So I use truncate function in params.
`Math.trunc(n)` to fix it.

Currently I use node v8.7.0.

**Comment by kaspesi** [comment]
Thanks I was having this problem too, must be a compatibility issue between the older version of node the book uses
